### ISSUE TITLE
Crash on first launch on iOS

### ISSUE THREAD

**Issue by jonasmunk** [arnesson/cordova-plugin-firebase#588]
Using this plugin I have experienced a lot of crashes. Looks like it happens at "first launch" - the first time the app gets a token. We can see in the stats that the apps crashed at first launch after this plugin was introduced - on subsequent launches it worked. The issue was first seen in a much older version of the plugin - but this stack trace is from the latest version 0.1.25.

It looks like some delegate selector is missing.

    2018-03-05 14:59:05.788864+0100 TV SYD[56640:4238699] -[FirebasePlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x60000106c480
    2018-03-05 14:59:05.806380+0100 TV SYD[56640:4238699] WARNING: GoogleAnalytics 3.14 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: -[FirebasePlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x60000106c480
    2018-03-05 14:59:05.839588+0100 TV SYD[56640:4238699] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
    2018-03-05 14:59:10.828508+0100 TV SYD[56640:4238699] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FirebasePlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x60000106c480'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x000000010a4c012b __exceptionPreprocess + 171
    	1   libobjc.A.dylib                     0x00000001093dcf41 objc_exception_throw + 48
    	2   CoreFoundation                      0x000000010a541024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
    	3   CoreFoundation                      0x000000010a442f78 ___forwarding___ + 1432
    	4   CoreFoundation                      0x000000010a442958 _CF_forwarding_prep_0 + 120
    	5   TV SYD                              0x0000000104dd6fa7 -[FIRMessaging defaultInstanceIDTokenWasRefreshed:] + 175
    	6   CoreFoundation                      0x000000010a45beac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    	7   CoreFoundation                      0x000000010a45bdaa _CFXRegistrationPost + 442
    	8   CoreFoundation                      0x000000010a45baf2 ___CFXNotificationPost_block_invoke + 50
    	9   CoreFoundation                      0x000000010a41d792 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
    	10  CoreFoundation                      0x000000010a41c90c _CFXNotificationPost + 652
    	11  Foundation                          0x0000000108e7050d postQueueNotifications + 856
    	12  CoreFoundation                      0x000000010a462c07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    	13  CoreFoundation                      0x000000010a462b5e __CFRunLoopDoObservers + 430
    	14  CoreFoundation                      0x000000010a446fc8 __CFRunLoopRun + 1224
    	15  CoreFoundation                      0x000000010a446889 CFRunLoopRunSpecific + 409
    	16  GraphicsServices                    0x0000000110beb9c6 GSEventRunModal + 62
    	17  UIKit                               0x000000010b74c5d6 UIApplicationMain + 159
    	18  TV SYD                              0x0000000104a63901 main + 65
    	19  libdyld.dylib                       0x000000010e0e0d81 start + 1
    	20  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException
    (lldb)

**Comment by soumak77** [comment]
duplicate of https://github.com/arnesson/cordova-plugin-firebase/issues/577

**Comment by jonasmunk** [comment]
I have now investigated it further...

The FIRMessagingDelegate defines a method...

messaging:(FIRMessaging *)messaging  didRefreshRegistrationToken:(NSString *)fcmToken)

... as non-optional in the version of Firebase used in the app...

https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/Firebase/Messaging/FirebaseMessaging.framework/Headers/FIRMessaging.h#L254

... but the method is not implemented in the delegate here: https://github.com/arnesson/cordova-plugin-firebase/blob/cc45b4deb4c203240795438921930b228eef4187/src/ios/AppDelegate%2BFirebasePlugin.m#L128

Can someone verify that this is what causes the crashes I experience - see the stack trace above?

Note it does not happen very often - and I cannot reproduce it locally currently.

**Comment by MaverickTech** [comment]
@jonasmunk I think I have the same issue, occurring on first launch. I can currently consistently replicate. The error consistently occurs if I delete the app, reinstall, and on first run I click the "Allow" for notifications in less than a second. Wait any longer and everything occurs normally.

Did you have any luck getting a fix?

**Comment by jonasmunk** [comment]
@MaverickTech I have not found a solution but I believe it is because of the missing method implementation.

I will try to replicate it using your procedure.

**Comment by TheKalin** [comment]
@MaverickTech  @jonasmunk You can mirage the crash by updating the iOS platform to 4.5.4. 
 It should return something like this in console instead of crashing the app. 
```
 - [Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x1c0287d50> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
```

**Comment by MaverickTech** [comment]
@TheKalin my project is already at iOS platform 4.5.4. It will crashes consistently on first launch. What plugin version and other component versions are you running?

**Comment by TheKalin** [comment]
@MaverickTech I have just changed the run scheme to release and it did not crash.

My env:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.4.0 browser 4.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v6.11.0
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

```
I'm using the GitHub repo version of the plugin
```
    <engine name="ios" spec="^4.5.4" />
    <plugin name="cordova-plugin-calendar" spec="^5.0.0" />
    <plugin name="cordova-plugin-device" spec="^1.1.4" />
    <plugin name="cordova-plugin-facebook4" spec="^1.9.1">
        <variable name="APP_ID" value="foo" />
        <variable name="APP_NAME" value="bar" />
    </plugin>
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-firebase" spec="git+https://github.com/arnesson/cordova-plugin-firebase.git" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1">
...
/>
    </plugin>
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
    <plugin name="cordova-plugin-nativegeocoder" spec="^2.0.4" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.1" />
    <plugin name="cordova.plugins.diagnostic" spec="^3.9.1" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
```

**Comment by jonasmunk** [comment]
I have just tried again - reinstall + quickly accept notification - and got the following log message without crashing...

`2018-03-20 08:41:38.079373+0100 TV SYD[311:42014] 4.10.0 - [Firebase/Messaging][I-FCM002023] The object <FirebasePlugin: 0x1c0293970> does not respond to -messaging:didReceiveRegistrationToken:, nor -messaging:didRefreshRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.`

I am currently using a recent fork of the master branch of the repo - so maybe it is fixed via the recent Firebase update.

I am still using `<engine name="ios" spec="^4.5.2" />` – so that cannot be the cause of it.

I did get a token but it still worries me to get that message - maybe the token changed without getting notified.

**Comment by TheKalin** [comment]
@jonasmunk ok so it looks like we have a temporary workaround for the issue, and is related with recents commits not the iOS platform update.

**Comment by jonasmunk** [comment]
@TheKalin Yes it looks to me like the Firebase module has changed behavior - so it will not crash but instead log a warning if the delegate method is missing.

**Comment by MaverickTech** [comment]
@jonasmunk @TheKalin Things are looking pretty good right now. Not been able to force a crash. 

I updated to the latest git version.

I can confirm the log message comes up when I click quickly. And consistent with @jonasmunk I am still getting a token, regardless of the log message.

**Comment by matgenois** [comment]
Will you bump the version so we can get the fix?

**Comment by soumak77** [comment]
should be fixed in version 1.0
